# Generated by Django 5.1.3 on 2024-12-31 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventlisting',
            name='organiser_id',
        ),
        migrations.RemoveField(
            model_name='eventlisting',
            name='place_id',
        ),
        migrations.AddField(
            model_name='eventlisting',
            name='place',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='travello.place'),
        ),
    ]
