# Generated by Django 5.1.3 on 2025-01-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_alter_eventlisting_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlisting',
            name='clicks',
            field=models.IntegerField(default=0),
        ),
    ]
